graphics

diff --git a/trunk/bin/jpg_fetch_and_scale b/trunk/bin/jpg_fetch_and_scale
--- a/trunk/bin/jpg_fetch_and_scale
+++ b/trunk/bin/jpg_fetch_and_scale
@@ -9,19 +9,17 @@ OVS_HOME=/share/Apps/oversight
 export PATH="$OVS_HOME/bin:$PATH"
 
 ARCH=
-case "`uname -a`" in 
-    *sigma\ *)
-        ARCH=nmt100
-        case "$CPU_MODEL" in
-            74K) ARCH=nmt200;;
-        esac
+if [ -f /mnt/syb8634/MIN_FIRMWARE_VER ] ;then
+    ARCH=nmt100
+    export PATH="$OVS_HOME/bin/$ARCH:$PATH"
+    export LD_LIBRARY_PATH="$OVS_HOME/bin/$ARCH:$LD_LIBRARY_PATH"
+else
+    if [ -f /nmt/apps/MIN_FIRMWARE_VER ] ; then
+        ARCH=nmt200
         export PATH="$OVS_HOME/bin/$ARCH:$PATH"
         export LD_LIBRARY_PATH="$OVS_HOME/bin/$ARCH:$LD_LIBRARY_PATH"
-        ;;
-esac
-
-echo $LD_LIBRARY_PATH
-
+    fi
+fi
 
 TMP=/share/Apps/oversight/tmp
 if [ ! -d $TMP ] ; then 
@@ -36,45 +34,50 @@ jpg_resize() {
     input="$1"
     type="$2"
     tv_mode="$3"
-    input_width="$4"
 
+    o=
     case "$type" in 
         fanart)
             case "$tv_mode" in 
-                hd) new_width=${input_width:-1280} ;; #add 1300
-                sd) new_width=${input_width:-900} ;; # 800 also 624 or 720!
-                *) echo "unknown tv_mode $tv_mode usage $0 file.jpg poster|fanart hd|sd [width]" ; exit 1 ;;
+                hd)   o="-width=1280 -height=720" ;;
+                sd) o="-width=685 -height=460" ;;
+                pal)  o="-width=685 -height=522" ;; # There is a a/r bug in gaya for pal display
             esac
             suffix=".$tv_mode.jpg"
             ;;
         poster)
-            new_width=300
+            o="-width=300"
             suffix=".jpg"
             ;;
-        *)
-            echo "unknown type $type usage $0 file.jpg poster|fanart hd|sd [width]"
-            exit 1
-            ;;
-        esac
+    esac
 
-    #get real width
-    old_width=`rdjpgcom -verbose "$input" | awk '/^JPEG image is/ { w=$4 ; sub(/w/,"",w) ; print w ; }'`
+    if [  X == "X$o" ] ; then
+        cat <<HERE
+  unknown type $type
+  usage: $0 file.jpg poster hd 
+         $0 file.jpg fanart hd|sd|pal [width]
+HERE
+        exit 1
+    fi
 
+    
     output=`echo "$input" | sed "s/\.jpg$/$suffix/"`
 
-    #scale it
-    echo djpeg -scale $new_width/$old_width "$input to $output"
-    if [ $new_width == $old_width ] ; then
-        ln -f "$input" "$output"
-    else
-        #Could use a pipe but input may = output so use tmp file.
-        djpeg -scale $new_width/$old_width "$input" > $TMP/$$ && cjpeg $TMP/$$ > "$output" && rm $TMP/$$
+
+    #Could use a pipe but input may = output so use tmp file.
+    # We always resize even if the dimensions are unchanged because it makes file size much smaller
+    INFO "$input | $o | $output" 
+    # Remove it first in case it was a hard link to the original file.
+    if djpeg "$input" | pnmscalefixed $o | cjpeg >  $TMP/$$.jpg && rm -f "$output" && mv $TMP/$$.jpg "$output"  ; then
         perms "$output"
+    else
+        ERROR "Unable to generate $output from $input using $o"
     fi
 }
 
-if [ -z "$3" ] ; then
+if [ "$1" != "start" -a -z "$3" ] ; then
 	echo "usage $0 [poster|fanart] url file wget options"
+	echo "usage $0 start"
 	exit 1
 fi
 
@@ -88,24 +91,43 @@ fetch_resize() {
     url="$1" ; shift;
     file="$1" ; shift ;
 
+    INFO "Processing : $type $url $file"
+
     if wget -O "$file" "$@" "$url"  ; then
         perms $file
         if [ -s "$file" ] ; then
-            case "$type" in
-                fanart)
-                    jpg_resize "$file" $type hd
-                    jpg_resize "$file" $type sd
-                    ;;
-                poster)
-                    jpg_resize "$file" $type sd
-                    ;;
-            esac
+            #resize_wait
+            resize_img "$type" "$file"  # &
         else
             rm -f "$file"
+            ERROR "Failed wget -O $file $@ $url"
         fi
     else
         rm -f "$file"
     fi
+}
+
+resize_wait() {
+   while running $Q.resizing ; do
+       sleep 2
+   done
+   echo $$ > $Q.resizing
+}
+
+resize_img() {
+    type="$1" ; shift; # poster or fanart
+    file="$1" ; shift ;
+    case "$type" in
+        fanart)
+            jpg_resize "$file" $type hd
+            jpg_resize "$file" $type pal
+            jpg_resize "$file" $type sd
+            ;;
+        poster)
+            jpg_resize "$file" $type sd
+            ;;
+    esac
+    rm -f "$Q.resizing"
 }
 
 Q=$TMP/resize.queue
@@ -122,49 +144,59 @@ add_queue() {
 }
 
 
-pid_file=$Q.pid
 running() {
-    if [ -f $pid_file ] ; then
-        if [ -d /proc/`cat $pid_file` ] ; then
+    if [ -f $1 ] ; then
+        if [ -d /proc/`cat $1` ] ; then
             return 0
         else
-            rm -f "$pid_file"
+            rm -f "$1"
         fi
     fi
     return 1
 }
 
 INFO() {
-    echo "[INFO] jpeg queue : $@"
+    echo "[INFO]`date +%H:%M:%S` jpeg queue : $@"
+}
+
+ERROR() {
+    echo "[ERROR]`date +%H:%M:%S` jpeg queue : $@"
 }
 
 
+pid_file=$Q.pid
 # Due to memory limits we process one request at a time.
-if running ; then
+if running $pid_file ; then
     add_queue  "$@"
 else
     echo $$ > $pid_file
 
-    add_queue  "$@"
+    if [ -n "$*" ] ; then
+        add_queue  "$@"
+    fi
 
-    while [ -f "$Q.pending" ] ; do
+    if [ `cat $pid_file` == $$ ] ; then 
 
-        mv "$Q.pending" "$Q.tmp"
-        cat "$Q.tmp" >> "$Q.processing"
-        chmod 666 "$Q.processing"
-        rm "$Q.tmp"
+        while [ -f "$Q.pending" ] ; do
 
-        while FS= read line ; do
+            mv "$Q.pending" "$Q.tmp"
+            cat "$Q.tmp" >> "$Q.processing"
+            chmod 666 "$Q.processing"
+            rm "$Q.tmp"
 
-            INFO " Unqueued : $line"
-            eval fetch_resize $line
+            while FS= read line ; do
 
-        done < "$Q.processing"
+                eval fetch_resize $line
 
-        rm -f "$Q.processing"
+            done < "$Q.processing"
 
-    done
+            rm -f "$Q.processing"
 
-    rm -f $pid_file
+
+        done
+
+        rm -f $pid_file
+        INFO "Shutting down"
+    fi
 fi
 
